#!/usr/bin/env python3
"""BMAD implementation story -> Ralph orchestrator spec (.ralph/specs/<story_key>.md)."""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def first_ready_for_dev(sprint_path: Path) -> str | None:
    text = sprint_path.read_text(encoding="utf-8")
    for line in text.splitlines():
        m = re.match(r"^\s{2}([0-9]+-[0-9]+-[\w-]+):\s+ready-for-dev\s*$", line)
        if m:
            return m.group(1)
    return None


def extract_sections(content: str) -> tuple[str, str]:
    ac_m = re.search(
        r"(?ms)^## Acceptance Criteria\s*\n(.*?)(?=^## |\Z)",
        content,
    )
    tasks_m = re.search(
        r"(?ms)^## Tasks / Subtasks\s*\n(.*?)(?=^## Dev Notes|^## References|^## Dev Agent|\Z)",
        content,
    )
    ac = ac_m.group(1).strip() if ac_m else ""
    tasks = tasks_m.group(1).strip() if tasks_m else ""
    return ac, tasks


def story_heading(content: str) -> str:
    for line in content.splitlines():
        if line.startswith("# Story "):
            return line[2:].strip()
    return "Unknown story"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Convert BMAD story markdown to a Ralph spec under .ralph/specs/.",
    )
    parser.add_argument(
        "story",
        nargs="?",
        type=Path,
        help="Path to story .md (default: first ready-for-dev in sprint-status)",
    )
    parser.add_argument(
        "--sprint-status",
        type=Path,
        default=Path("_bmad-output/implementation-artifacts/sprint-status.yaml"),
    )
    parser.add_argument(
        "--implementation-artifacts",
        type=Path,
        default=Path("_bmad-output/implementation-artifacts"),
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path(".ralph/specs"),
    )
    args = parser.parse_args()
    root = Path.cwd()
    sprint_path = root / args.sprint_status
    impl_dir = root / args.implementation_artifacts

    if args.story:
        story_path = Path(args.story)
        if not story_path.is_absolute():
            story_path = (root / story_path).resolve()
    else:
        if not sprint_path.is_file():
            print(f"Missing sprint status: {sprint_path}", file=sys.stderr)
            return 1
        key = first_ready_for_dev(sprint_path)
        if not key:
            print(
                "No ready-for-dev story in sprint-status; pass a story path.",
                file=sys.stderr,
            )
            return 1
        story_path = impl_dir / f"{key}.md"
        if not story_path.is_file():
            print(f"Story file not found: {story_path}", file=sys.stderr)
            return 1

    if not story_path.is_file():
        print(f"Not a file: {story_path}", file=sys.stderr)
        return 1

    content = story_path.read_text(encoding="utf-8")
    key = story_path.stem
    title = story_heading(content)
    ac, tasks = extract_sections(content)

    try:
        rel_source = str(story_path.relative_to(root))
    except ValueError:
        rel_source = str(story_path)

    out_dir = root / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{key}.md"

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    body = f"""---
story_key: {key}
source_story: {rel_source}
generated_at: {now}
completion_promise: LOOP_COMPLETE
---

# Ralph spec: {title}

Generated by `scripts/bmad_to_ralph.py`. Re-run after editing the BMAD story.

## Source

BMAD story: `{rel_source}`

## Success criteria

Stop the Ralph loop when `bash scripts/verify.sh` passes and every acceptance criterion in the story is done.

## Acceptance criteria (from story)

{ac if ac else "(none extracted)"}

## Tasks / subtasks (from story)

{tasks if tasks else "(none extracted)"}

## Operator hints

- `ralph.yml` should set `core.specs_dir` to `.ralph/specs/` (see repo root).
- Use `PROMPT.md` or explicit `ralph run` instructions for the active story.
"""
    out_path.write_text(body, encoding="utf-8", newline="\n")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
